02/01/2023 09:40:05|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 09:40:06|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 09:40:16|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 09:41:20|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 09:41:21|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 09:41:30|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 10:04:53|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 11:20:47|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 11:20:50|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 13:49:57|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 13:53:26|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 13:56:15|ERROR   |root                            |BAZARR Error trying to get series from Sonarr. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 72, in create_connection\n    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):\n  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo\n    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):\nsocket.gaierror: [Errno -3] Try again\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 398, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 239, in request\n    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n  File "/usr/lib/python3.10/http/client.py", line 1282, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output\n    self.send(msg)\n  File "/usr/lib/python3.10/http/client.py", line 975, in send\n    self.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 205, in connect\n    conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc4caebe860>: Failed to establish a new connection: [Errno -3] Try again\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 489, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=\'http\', port=80): Max retries exceeded with url: //***.***.***.***:8989/api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false&apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7fc4caebe860>: Failed to establish a new connection: [Errno -3] Try again\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/sonarr/filesystem.py", line 23, in browse_sonarr_filesystem\n    r = requests.get(url_sonarr_api_filesystem, timeout=60, verify=False, headers=headers)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host=\'http\', port=80): Max retries exceeded with url: //***.***.***.***:8989/api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false&apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7fc4caebe860>: Failed to establish a new connection: [Errno -3] Try again\'))'|
02/01/2023 13:57:27|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 13:57:47|ERROR   |root                            |BAZARR Error trying to get series from Radarr. Connection Error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 174, in _new_conn\n    conn = connection.create_connection(\n  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/http.py", line 325, in patched_create_connection\n    return _orig_create_connection(address, *args, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 95, in create_connection\n    raise err\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/connection.py", line 85, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 703, in urlopen\n    httplib_response = self._make_request(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 398, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 239, in request\n    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n  File "/usr/lib/python3.10/http/client.py", line 1282, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output\n    self.send(msg)\n  File "/usr/lib/python3.10/http/client.py", line 975, in send\n    self.connect()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 205, in connect\n    conn = self._new_conn()\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connection.py", line 186, in _new_conn\n    raise NewConnectionError(\nurllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc4c43edab0>: Failed to establish a new connection: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 489, in send\n    resp = conn.urlopen(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/connectionpool.py", line 787, in urlopen\n    retries = retries.increment(\n  File "/app/bazarr/bin/bazarr/../libs/urllib3/util/retry.py", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host=\'***.***.***.***\', port=7878): Max retries exceeded with url: /api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false&apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7fc4c43edab0>: Failed to establish a new connection: [Errno 111] Connection refused\'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/radarr/filesystem.py", line 24, in browse_radarr_filesystem\n    r = requests.get(url_radarr_api_filesystem, timeout=60, verify=False, headers=headers)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 73, in get\n    return request("get", url, params=params, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/api.py", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 587, in request\n    resp = self.send(prep, **send_kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/sessions.py", line 701, in send\n    r = adapter.send(request, **kwargs)\n  File "/app/bazarr/bin/bazarr/../libs/requests/adapters.py", line 565, in send\n    raise ConnectionError(e, request=request)\nrequests.exceptions.ConnectionError: HTTPConnectionPool(host=\'***.***.***.***\', port=7878): Max retries exceeded with url: /api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false&apikey=(removed) (Caused by NewConnectionError(\'<urllib3.connection.HTTPConnection object at 0x7fc4c43edab0>: Failed to establish a new connection: [Errno 111] Connection refused\'))'|
02/01/2023 13:57:52|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 13:57:52|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 16:21:57|WARNING |apscheduler.executors.default   |Run time of job "Update Movie list from Radarr (trigger: interval[1:00:00], next run at: 2023-01-02 16:48:26 GMT)" was missed by 0:33:30.056577|
02/01/2023 16:21:57|WARNING |apscheduler.executors.default   |Run time of job "Update Series list from Sonarr (trigger: interval[1:00:00], next run at: 2023-01-02 16:50:32 GMT)" was missed by 0:31:24.059282|
02/01/2023 16:21:57|WARNING |apscheduler.executors.default   |Run time of job "Sync episodes with Sonarr (trigger: interval[1:00:00], next run at: 2023-01-02 16:54:06 GMT)" was missed by 0:27:50.061118|
02/01/2023 16:27:23|INFO    |root                            |BAZARR Finished searching for missing Movies Subtitles. Check History for more information.|
02/01/2023 16:58:23|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 16:58:36|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 16:58:36|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 16:58:36|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 16:58:36|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 16:58:36|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 17:44:03|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 17:44:12|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 17:44:12|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 17:44:12|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 17:44:12|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 17:44:13|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 18:02:07|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 18:02:07|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 18:02:07|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 18:02:07|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 18:02:07|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 18:15:27|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 18:15:27|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 18:52:24|WARNING |apscheduler.executors.default   |Run time of job "Update Series list from Sonarr (trigger: interval[1:00:00], next run at: 2023-01-02 19:51:31 GMT)" was missed by 0:00:52.680354|
02/01/2023 18:53:55|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/app/bazarr/bin/bazarr/app/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 1021, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/morpheus65535/Bazarr/releases?per_page=100'|
02/01/2023 18:54:10|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 18:54:10|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 18:54:10|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 18:54:10|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 18:54:10|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 19:05:10|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 19:05:10|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 19:05:10|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:05:11|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 19:05:11|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
02/01/2023 19:06:50|INFO    |root                            |BAZARR trying to connect to Sonarr SignalR feed...|
02/01/2023 19:06:50|INFO    |root                            |BAZARR trying to connect to Radarr SignalR feed...|
02/01/2023 19:06:50|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
02/01/2023 19:06:50|INFO    |root                            |BAZARR SignalR client for Radarr is connected and waiting for events.|
02/01/2023 19:06:50|INFO    |root                            |BAZARR SignalR client for Sonarr is connected and waiting for events.|
